services:
  react:
    image: node:24-alpine
    container-name: pm20261-node-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src
    command: npm run dev -- --host 0.0.0.0
    networks:
      - pm20261-network

  mysql:
    image: mysql:8.0
    container_name: pm20261-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pm20261pass
      MYSQL_DATABASE: pm20261
      MYSQL_USER: pm20261user
      MYSQL_PASSWORD: pm20261userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pm20261-network


  mongodb:
    image: mongo:7.0
    container_name: pm20261-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pm20261user
      MONGO_INITDB_ROOT_PASSWORD: pm20261pass
      MONGO_INITDB_DATABASE: pm20261
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pm20261-network
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: pm20261-portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - pm20261-network

volumes:
  mysql_data:
  mongodb_data:
  portainer_data:

networks:
  pm20261-network:
    driver: bridge
